name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
        #   get-test:
        #     name: get-test 
        #     runs-on: ubuntu-20.04
        #     steps:
        #       - uses: actions/checkout@v3
        #         with:
        #           repository: ${{ secrets.REPO }}
        #           token: ${{ secrets.ACCESS_TOKEN }}
        #       - uses: actions/upload-artifact@v2
        #         with:
        #           name: test
        #           path: .

  set-up-test:
    name: set-up-test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: cache-depend-check
        id: cache-depend
        uses: actions/cache@v3
        with:
          path: $HOME/.local
          key: ${{ runner.os }}-cache-depend
      - name: check-cache
        if: steps.cache-depend.outputs.cache-hit != 'true'
        run: |
          chmod +x ${GITHUB_WORKSPACE}/.github/classroom/install_depend.sh
          ${GITHUB_WORKSPACE}/.github/classroom/install_depend.sh
        shell: bash

      - name: add to Path
        run: |
          echo "${HOME}/.local/qemu/bin" >> $GITHUB_PATH
          echo "${HOME}/.local/gnu-riscv/bin" >> $GITHUB_PATH
          echo "${HOME}/.local/qemu/lib" >> '$LD_LIBRARY_PATH'
          echo "${HOME}/.local/gnu-riscv/lib" >> '$LD_LIBRARY_PATH'
      
      - name: install-valgrind
        run: |
          sudo apt-get update
          sudo apt-get install valgrind
      
      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: install-pip-depend
        run: pip install -r ${GITHUB_WORKSPACE}/.github/classroom/requirement.txt
      
      - name: download-artifact
        uses: actions/download-artifact@v2

      - name: check-path
        run: |
          echo $PATH
          echo $LD_LIBRARY_PATH
          riscv64-unknown-elf-gcc --version
      
      - name: do-testing  
        uses: education/autograding@v1 
      #  set-up-xv6:
      #    runs-on: ubuntu-20.04
      #    steps:
      #    - uses: actions/checkout@v3
      #    - name: script
      #      run: |
      #        chmod +x ./handout/install-riscv-tools.sh
      #        ./handout/install-riscv-tools.sh
      #      shell: bash
 
        #  set-up-python:
        #    name: set-up-python 
        #    needs: get-test
        #    runs-on: ubuntu-20.04
        #    steps:
        #      - uses: actions/checkout@v3
        #      - uses: actions/setup-python@v4
        #        with:
        #          python-version: '3.9'
        #      - run: pip install -r ${GITHUB_WORKSPACE}/.github/classroom/requirement.txt
        #      - uses: actions/download-artifact@v2
        #      - run: ls
        #  test:
        #    needs: [set-up-python,set-up-xv6]
        #    name: Autograding
        #    runs-on: ubuntu-20.04
        #    steps:
        #      - uses: actions/checkout@v3
        #      - uses: actions/download-artifact@v2
        #      - uses: education/autograding@v1 
